version: '3.7'

services:
  order-ws:
    image: order-ws:latest
    container_name: order-ws
    build: .
    ports:
      - '8099:8099'
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mvp-network

  database:
    image: 'postgres:latest'
#    restart: always
    container_name: 'db'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      TZ: 'America/Sao_Paulo'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
    volumes:
      - ./src/main/resources/database/1_create_tables.sql:/docker-entrypoint-initdb.d/1_create_tables.sql
      - ./src/main/resources/database/2_inserts_category.sql:/docker-entrypoint-initdb.d/2_inserts_category.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - mvp-network

networks:
  mvp-network:
    driver: bridge