apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    app: delivery
#  annotations:
#    kubernetes.io/ingress.class: alb
spec:
  selector:
    app: delivery
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8099
      nodePort: 32000
      protocol: TCP