apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: delivery
#  annotations:
#    kubernetes.io/ingress.class: alb
spec:
  selector:
    app: delivery
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: 32000
      protocol: TCP